### ISSUE TITLE
npm install bip-ed25519 - not found

### ISSUE THREAD

**Issue by nicarq** [ilap/cwag#1]
Hi!

Thanks for sharing :) it’s not currently working for me, because bip-ed25519 is missing in the package.json dependencies. If I try to install it manually by doing npm install bip-ed25519, I get that it wasn’t found :-/

**Comment by cryptophonic** [comment]
apply the following patch to package.json and redo the "npm install"

```
-    "scrypt": "^6.0.3"
+    "scrypt": "^6.0.3",
+    "bip-ed25519": "git@github.com:ilap/BIP32-Ed25519.git"
```

**Comment by nicarq** [comment]
@mjackson001 thanks!

**Comment by gufmar** [comment]
ok, this brought my one important step forward. When I tried this script around a month ago I wasn't able to get this bip-ed25519 installed. (the package.json at that time contained a bip-ed25519 name, but that pointed to another URL.

npm debug.log at that time looked like 

```
92 warn cwag@0.0.1 No repository field.
93 verbose stack Error: bip-ed25519@0.0.1 install: `node-gyp rebuild`
93 verbose stack Exit status 1
93 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
93 verbose stack     at emitTwo (events.js:126:13)
93 verbose stack     at EventEmitter.emit (events.js:214:7)
93 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
93 verbose stack     at emitTwo (events.js:126:13)
93 verbose stack     at ChildProcess.emit (events.js:214:7)
93 verbose stack     at maybeClose (internal/child_process.js:925:16)
93 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
94 verbose pkgid bip-ed25519@0.0.1
95 verbose cwd C:\Users\mgu\Documents\cwag
96 verbose Windows_NT 10.0.17134
97 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "bip-ed25519"
98 verbose node v8.11.2
99 verbose npm  v5.6.0
100 error code ELIFECYCLE
101 error errno 1
102 error bip-ed25519@0.0.1 install: `node-gyp rebuild`
102 error Exit status 1
103 error Failed at the bip-ed25519@0.0.1 install script.
```

after quite a lot of time spend on this (as a newbie) I gave up at that time.

Now it's a different error and it looks more like I'm not allowed to fetch this package from git@github.com:ilap/BIP32-Ed25519.git

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'i',
1 verbose cli   'bip-ed25519' ]
2 info using npm@5.6.0
3 info using node@v8.11.2
4 verbose npm-session 07fc847a1f678ef6
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData error for bip-ed25519@git+ssh://git@github.com/ilap/BIP32-Ed25519.git Error while executing:
7 silly fetchPackageMetaData C:\Program Files\Git\cmd\git.EXE ls-remote -h -t ssh://git@github.com/ilap/BIP32-Ed25519.git
7 silly fetchPackageMetaData
7 silly fetchPackageMetaData Host key verification failed.
7 silly fetchPackageMetaData fatal: Could not read from remote repository.
7 silly fetchPackageMetaData
7 silly fetchPackageMetaData Please make sure you have the correct access rights
7 silly fetchPackageMetaData and the repository exists.
7 silly fetchPackageMetaData
7 silly fetchPackageMetaData exited with error code: 128
```

when I try to run the git command in cli i get this error

```
The authenticity of host 'github.com (192.30.253.113)' can't be established.
RSA key fingerprint is SHA256:nThbg6[redacted]6E5SY8.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.253.113' (RSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights and the repository exists.
```

**Comment by cryptophonic** [comment]
this would be a permission issue with ssh / github.  see if this helps: https://help.github.com/articles/error-permission-denied-publickey/

**Comment by gufmar** [comment]
I'm still struggling with this (my) issue. (Windows 10 PC)
privatekey is generated, publickey is stored on my git profile 
`ssh -vT git@github.com` shows a good looking "Hi gufmar! You've successfully..." 

but still both `npm install bip32-ed25519` and `git ls-remote -h -t ssh://git@github.com/ilap/BIP32-Ed25519.g` does show the same errors as reported above.

I was able to run `npm install git+https://git@github.com/ilap/BIP32-Ed25519.git`

But this now results in these warnings and errors

```
..\src\ed25519.c(167): warning C4013: 'htonl' undefined; assuming extern returning int C:\Users\mgu\Documents\cwag\node_modules\bip-ed25519\build\bip-ed25519.vcxproj]
..\src\ed25519.c(168): warning C4013: 'printf' undefined; assuming extern returning int 
 C:\Users\mgu\Documents\cwag\node_modules\bip-ed25519\build\bip-ed25519.vcxproj]
  bip-ed25519.cc
  win_delay_load_hook.cc
     Creating library C:\Users\mgu\Documents\cwag\node_modules\bip-ed25519\build\Release\bip-ed25519.lib and object C:\Users\mgu\Documents\cwag\node_modules\bip-ed25519\build\Release\bip-ed25519.exp
ed25519.obj : error LNK2001: unresolved external symbol htonl [C:\Users\mgu\Documents\cwag\node_modules\bip-ed25519\build\bip-ed25519.vcxproj]
C:\Users\mgu\Documents\cwag\node_modules\bip-ed25519\build\Release\bip-ed25519.node : fatal error LNK1120: 1 unresolved
 externals [C:\Users\mgu\Documents\cwag\node_modules\bip-ed25519\build\bip-ed25519.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\mgu\Documents\cwag\node_modules\bip-ed25519
gyp ERR! node -v v8.11.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN cwag@0.0.1 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bip-ed25519@0.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
```

**Comment by cryptophonic** [comment]
I see you're on Windows.  I don't have any Windows machines to test with, but I expect that might be part of, if not the entire issue.  I install OK running Linux here.

**Comment by gufmar** [comment]
ok, I read some docs and even if my last lines of cpp code were written in the former millennium, if found adding this 3 lines (2 inlcudes and one pragma lib link) allowed me to compile and install the package.

https://github.com/gufmar/BIP32-Ed25519/commits/master/src/ed25519.c

I have no idea if this is fully correct and save, or if it will break functionality on other environments.
